### ISSUE TITLE
dsymutil warning: could not find object file symbol for symbol ___divdc3

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#14]
This one is a very minor warning, I'm filing it here so it does not get lost…

```
$ cat a.c
int main()
{
  volatile _Complex double foo;
  foo = (_Complex double)(3.+4.i);
  foo *= (_Complex double)(2);
  if (foo != (_Complex double)(6+8i)) __builtin_abort();
  foo = (_Complex double)(3.+4.i);
  foo /= (_Complex double)(2);
  if (foo != (_Complex double)(1.5+2i)) __builtin_abort();
}
$ ./bin/gcc a.c
$ ./bin/gcc a.c -g
warning: (arm64)  could not find object file symbol for symbol ___divdc3
```

The warning comes from `dsymutil`:

```
dsymutil a.out
warning: (arm64)  could not find object file symbol for symbol ___divdc3
```

**Comment by iains** [comment]
this is a long-standing ld64 bug (fixed in my versions in 'xtools' on here) - I reported it (with a reproducer) to the Apple folks more than a year ago, but still not fixed in latest Xcode.

what happens is that when code is conditionally compiled from the same source, only the first reference to the object/source pair gets included in ld64's output - so that dsymutil has no idea where to find the second symbol.
