### ISSUE TITLE
Nested functions

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#26]
This may be the cause for some crashes in procedure pointers in Fortran. In any case, here is a C crasher:

```
$ cat a.c
void foo(void) {
  void bar(void) { ; }
  void (*pptr)(void);
  pptr = bar;
  pptr();
}

int main (void) {
  foo();
}
$ ./bin/gcc a.c -O1 && ./a.out
$ ./bin/gcc a.c -O0 && ./a.out
zsh: segmentation fault  ./a.out
```

**Comment by fxcoudert** [comment]
This is the cause for the only `libgomp` failure: `libgomp.c/pr52547.c`

**Comment by iains** [comment]
could you try your case with "-fno-trampolines" ?
I'm rebuilding everything at the moment.

**Comment by iains** [comment]
ah, never mind, it seems that this might only be implemented for Ada.

**Comment by apinski-cavium** [comment]
Most likely the following needs to be added (when initializing the trampoline):
#ifdef HAVE_ENABLE_EXECUTE_STACK
  emit_library_call (gen_rtx_SYMBOL_REF (Pmode, "__enable_execute_stack"),
                     LCT_NORMAL, VOIDmode, XEXP (m_tramp, 0), Pmode);
#endif

Like what is done on i386, etc.
Once I get a build going, I will test a patch for that.

**Comment by apinski-cavium** [comment]
[fixtrampolines.diff.txt](https://github.com/iains/gcc-darwin-arm64/files/6424679/fixtrampolines.diff.txt)
This is the start of the patch, there might need some other stuff like libgcc changes done too.

**Comment by iains** [comment]
executable stack is prohibited by the kernel - I've hacked in a temporary solution using the "ada" method, but  it uses bit 1 of the address, which is non-ABI-compliant.

**Comment by iains** [comment]
current hacks:
https://github.com/iains/gcc-darwin-arm64/commit/8408ba82ea0cde27e3fdb01a5ed224daf4843712
https://github.com/iains/gcc-darwin-arm64/commit/3fdef6d50954dd9743bee792682459b9e187ebbc
https://github.com/iains/gcc-darwin-arm64/commit/0246f34e48e55b1a821f9dc08d1ba57e1b38b71b

Future plans:

While security policy does not allow executable stack, it does allow for dynamic code generation.  This would mean that we can have allocated trampolines (either from a pool or some other way) but it also means that the usage needs to be tracked, since freeing the is no longer "automatic" on scope exit.

So one of my colleagues from embecosm is looking into the following skeleton design (we plan to publish a "GCC12 project" to do this, since it should be useful to other platforms that would prefer to avoid executable stack for security reasons) -- not ready yet tho : 

- the front end(s) need to be ready to emit markers on nested structures that reflect the target’s choice of lowering

- the middle end (gcc/nested.c) needs to react to those

 * in particular the new piece of work is tracking nested function scopes so that a cleanup may be added (it might be relatively simple to implement, e.g. using a gimple with_cleanup operation)
 * inventing the builtin to control that cleanup
 * I think that there are compiler builtins to deal with trampoline and descriptor cases, but this might need a hybrid (since we have a descriptor for a trampoline that is not on the stack - so the descriptor doesn’t completely replace the trampoline like the Adacode solution … although they do still use the trampoline builtin stuff in some way)

- the back end(s) need to deal with the allocation / generation / deallocation of the trampolines at the appropriate pass (possibly expand?)
-

**Comment by iains** [comment]
https://github.com/iains/gcc-darwin-arm64/commit/c0f7a8feebb615f2e8fc7d5bc6ba6cb40285ae80

includes the proposed (and posted) replacement implementation which uses a heap-allocated trampoline.

**Comment by crazypill** [comment]
Thank you! Thank you! Thank you!

I’ve been hoping and praying for this fix and it’s a new year miracle!

I really appreciate all the work you and the community have been putting into porting gcc/gfortran to Apple M1.

Without this latest fix, WSJT-X (a weak signal ham radio application used by 1000’s of hams) would crash due to nested function callback and non-executable stack.  I’ve been trying to get the app running native and this was a big stumbling block for me.  Now it finally decodes without crashing!

Thanks again for the great work-  best wishes for the New Year.
alex

**Comment by fxcoudert** [comment]
There are no known failures with nested functions in the new implementation. Closing this.

**Comment by Nicholaswogan** [comment]
@fxcoudert when do you expect hombrew binaries to be updated with an Apple Silicon gfortran that works with nested functions?

**Comment by fxcoudert** [comment]
I was aiming at the next GCC 11 minor release. Or waiting for GCC 12. Since the new scheme is incompatible with the previous (partial) implementation, and even though we always labeled support in GCC 11 as experimental, I'm a bit worried about breaking code for current users.

**Comment by Nicholaswogan** [comment]
@fxcoudert I hear GCC 12 will come out in April 2022. Will updated Apple Silicon GCC binaries be available then as well?
