### ISSUE TITLE
Calls from Fortran to C

### ISSUE THREAD

**Issue by kalibera** [iains/gcc-darwin-arm64#32]
When Fortran code gets a pointer to a C function and tries to call it and bit 2 of the function pointer happens to be set, it updates that pointer making it invalid, causing the call to crash.

This can be reproduced using an [example](https://github.com/iains/gcc-darwin-arm64) from GCC documentation on how to call back from Fortran to C.

C (c.c):

```
// https://gcc.gnu.org/onlinedocs/gfortran/Working-with-Pointers.html

#include <stdio.h>

/* Procedure implemented in Fortran.  */
void get_values (void (*)(double));

/* Call-back routine we want called from Fortran.  */
static void
print_it (double x)
{
  printf ("Number is %f.\n", x);
}

/* Call Fortran routine and pass call-back to it.  */
int main (int argc, char **argv)
{
  unsigned long x = (unsigned long)&print_it;
  fprintf(stderr, "Bit 2 of function pointer: %lu\n", x&4);
  get_values (&print_it);
  return 0;
}
```
Fortran (f.f90):

```
MODULE m
  IMPLICIT NONE

  ! Define interface of call-back routine.
  ABSTRACT INTERFACE
    SUBROUTINE callback (x)
      USE, INTRINSIC :: ISO_C_BINDING
      REAL(KIND=C_DOUBLE), INTENT(IN), VALUE :: x
    END SUBROUTINE callback
  END INTERFACE

CONTAINS

  ! Define C-bound procedure.
  SUBROUTINE get_values (cproc) BIND(C)
    USE, INTRINSIC :: ISO_C_BINDING
    TYPE(C_FUNPTR), INTENT(IN), VALUE :: cproc

    PROCEDURE(callback), POINTER :: proc

    ! Convert C to Fortran procedure pointer.
    CALL C_F_PROCPOINTER (cproc, proc)

    ! Call it.
    CALL proc (1.0_C_DOUBLE)
    CALL proc (-42.0_C_DOUBLE)
    CALL proc (18.12_C_DOUBLE)
  END SUBROUTINE get_values

END MODULE m
```
Executed as:

```
gfortran -O0 -g -c f.f90 -o f.o
clang -O0 -g -c c.c -o c.o
clang -o test c.o f.o
./test
```
Output:

```
Bit 2 of function pointer: 4
Bus error: 10
```
Corresponding generated code:

```
;   SUBROUTINE get_values (cproc) BIND(C)
       0: fd 7b bd a9                   stp     x29, x30, [sp, #-48]!
       4: fd 03 00 91                   mov     x29, sp
       8: e0 0f 00 f9                   str     x0, [sp, #24]
;     CALL C_F_PROCPOINTER (cproc, proc)
       c: e0 0f 40 f9                   ldr     x0, [sp, #24]
      10: e0 17 00 f9                   str     x0, [sp, #40]
;     CALL proc (1.0_C_DOUBLE)
      14: e0 17 40 f9                   ldr     x0, [sp, #40]
      18: 01 00 7e 92                   and     x1, x0, #0x4  <======= testing bit 2
      1c: 3f 00 00 f1                   cmp     x1, #0
      20: 60 00 00 54                   b.eq    #12 <ltmp0+0x2c> <==== jump if 0 (aligned)
      24: 10 c0 5f f8                   ldur    x16, [x0, #-4] <====== set x16 (never used)
      28: 00 40 40 f8                   ldur    x0, [x0, #4] <======== translate x0 producing an invalid pointer
      2c: 00 10 6e 1e                   fmov    d0, #1.00000000
      30: 00 00 3f d6                   blr     x0 <================== the call (crashes)
```
A workaround for this is to compile the C code with `-falign-functions=8`, so that bit 2 of the pointer is not set and one gets this output:

```
Bit 2 of function pointer: 0
Number is 1.000000.
Number is -42.000000.
Number is 18.120000.
```
This issue is not specific to ISO_C_BINDING. It also appears in old-style non-portable Fortran code which calls to C via a function (procedure) pointer passed as EXTERNAL, causing crashes of a number of R CRAN packages (found by Brian Ripley). 

The problem was found with Apple clang, but it should apply any time the C function is not aligned to 64 bytes, with any C compiler.

**Comment by iains** [comment]
I am 99% sure that this is fall-out from using the work-around for nested function.

Synopsis:
We cannot use stack trampolines on Arm64-darwin; the kernel prohibits executable stack.

There is a solution used with Ada (which is what we've temporarily added for Fortran) that uses a *NON-ABI-COMPLIANT* mechanism for identifying function pointers that require the static chain register to be setup.  This tests a specific bit in the address.  For many architectures this can work (despite the non-abi conformance) because function call addresses are usually aligned to > 1 byte.

However. Arm already has meaning for bit 0 (and reserves use of bit 1).  As you are observing, the generic alignment applied to functions is not sufficient to allow the use of a non-reserved bit.  For Fortran calling Fortran there's no issue (since the work-around also bumps the alignment for Fortran functions).  However, we call C .. 

The workaround you mention is valid - but that can't fix any cases in installed libraries.  However, FWIW, I think I checked the addresses of libSystem &c and didn't see any that would be a problem (relevance: imagine someone passes a pointer to a libSystem function as a callback).

A proper fix for nested functions that doesn't require a stack trampoline is somewhat more involved since it involves adding cleanups to scopes with nested functions - I can see a solution - but time is ever a problem.  This applies to the type of scheme used by libFFI and Objective-C and also to an alternate I have in mind that doesn't need a helper dylib.

**Comment by fxcoudert** [comment]
@iains this is apparently hitting scipy hard (see https://github.com/Homebrew/homebrew-core/pull/70096)

As I understand, the need for stack trampolines is limited to nested functions in C (not standard C), contained procedures in the main program in Fortran (standard, but relatively rare), and Ada. The current workaround, on the other hand, significantly breaks all Fortran-to-C calls.

Therefore, I would recommend prioritising Fortran-to-C calls (there are a lot in published code) rather than contained procedures in the main program.

**Comment by iains** [comment]
Adjusted the nested function hack to use bit 1 rather than bit 2 - which makes the inter-op work without adjusting the C build conditions.   It remains a hack (using a reserved bit) but perhaps a more compatible hack.

02d30eeb2534a593216564c07e94f4d49f0b679e

**Comment by kalibera** [comment]
Thanks!
