### ISSUE TITLE
11.2.0 backport issue with libgcc_s1.1.

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#50]
The current gcc-11 backport (which I updated to gcc 11.2.0 in https://github.com/fxcoudert/gcc/tree/gcc-11.2.0-arm-20211123), which is working nicely on ARM Big Sur and Intel Monterey, fails to build on ARM Monterey.

The issue is the following:

```
configure:4074: ./conftest
dyld[78308]: Library not loaded: @rpath/libgcc_s.1.1.dylib
  Referenced from: /private/tmp/gcc-20211123-41856-gy4s74/gcc-gcc-11.2.0-arm-20211123/build/aarch64-apple-darwin21/libgomp/conftest
  Reason: tried: '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)
/private/tmp/gcc-20211123-41856-gy4s74/gcc-gcc-11.2.0-arm-20211123/libgomp/configure: line 4076: 78308 Abort trap: 6           ./conftest$ac_cv_exeext
```

I'm not sure why it manifests itself only on ARM Monterey (and not ARM Intel, or ARM Big Sur). I know that you're working on rpaths Iain, so I guess my question is: is there a quick fix for that build issue that can be backported to 11.2?

For example, would that patch be standalone/sufficient? https://github.com/iains/gcc-darwin-arm64/commit/190027c08e5d0eb623929ad02f92508fe5f7a8af

Any help will be appreciated.

**Comment by iains** [comment]
I don't have access to Arm Darwin21 (gcc304 is on darwin20.4).

The rpaths I have applied is a series not a single patch - and we are now working towards an "official" version
there's also patch set recently applied to master that fixes the EH hassles (80556).

perhaps something is firing there that previously was not used - e.g. something in a spec or so.

1. what does "otool -lv libgomp.xxxx.dylib" show for rpaths?
2.. I thought that /usr/local was not the install path for arm Homebrew
3. please run the command lines for the conftest that fails and then do "otool -lv conftest" and list the rpaths included

(at build-time) conftest _should_ have rpaths for 'gcc' (which should find libgcc_s.1.1.dylib) and any dependent libs we expect to use - which correspond to -B options for the build-time paths where the libraries are (so there should be an rpath for the libgomp/.libs dir *if* we expect to use that).

If nothing obvious drops out of this - perhaps it's better if I do a backport of the current WIP and any dependent patches (I have a local list of stuff that's been applied) - you prefer 11.2 release, rather than a snapshot?

Obv. the work towards an 'official' arm branch is taking precedence - but AFAIK everything needed (so far) is back-portable - even if not officially, it should be technically.  The arm port has always used @rpath so there should not be any conflict.

**Comment by ilg-ul** [comment]
> The current gcc-11 backport (which I updated to gcc 11.2.0 in https://github.com/fxcoudert/gcc/tree/gcc-11.2.0-arm-20211123)

Oops! Yesterday I just finished the xPack GCC 11.1 build based on your repo, but did not release it yet. Should I redo it with 11.2, or should I still wait a bit?

**Comment by iains** [comment]
I just had a quick look on [master/gcc12] aarch64 darwin20, and the libgomp there does not have a dep. on the shared libgcc_s.1.1.. so that's something to look into - will try to do so this evening.

**Comment by iains** [comment]
just started a test build on gcc304 - so it looks like output will not happen until tomorrow (assuming all goes well) at the earliest ...

**Comment by fxcoudert** [comment]
> Yesterday I just finished the xPack GCC 11.1 build based on your repo

I have no idea what "xPack GCC" is, but from the website it appears to be a cross-compiler hosted on macOS but targeting non-macOS ARM. If so, I do not think you will be hit by any of these issues, which are target-dependent.

**Comment by iains** [comment]
Actually, cross-compilers hosted on M1 do need some of the patches (applied to master already) - because the *host* has to work.

I am just testing a branch with
[1] current list of back ports
[2] current immediate WIP for *darwin*
[3] current aarch64 port.

Note we have closed the gap between [3] and tip of master, but that inevitably means that the back port list is longer (not unusual for this part of the phase - most of the fixes for config/bad code/abi in stage1 are relevant).

A few hours, hopefully..

**Comment by ilg-ul** [comment]
> I have no idea what "xPack GCC" is, but from the website it appears to be a cross-compiler hosted on macOS but targeting non-macOS ARM. If so, I do not think you will be hit by any of these issues, which are target-dependent.

Hi Francois, xPack GCC is a cross-platform GCC binary distribution (https://github.com/xpack-dev-tools/gcc-xpack).

The current public release is based on the public 11.2.0, but when I wanted to add support for Apple Silicon, I had to go back to 11.1, and used `gcc-11.1.0-arm-20210504` (https://github.com/xpack-dev-tools/gcc-xpack/blob/4efa00e2f5e76da9292997758e0ba8343d656b3b/scripts/common-apps-functions-source.sh#L32-L33).

I few days ago I finished building all binaries for all platforms, but before making them public, I noticed your announcement of `gcc-11.2.0-arm-20211123`.

I'd prefer to avoid releasing a 11.1 package after already having a 11.2, since this creates a versioning confusion; so, if you think it is ok, I'd update the scripts to use `gcc-11.2.0-arm-20211123` and rebuild. If you are still working on the details and plan a new release, I can wait a few more days.

**Comment by fxcoudert** [comment]
1. The build is configured with: `../gcc/configure --prefix=/tmp/homebrew/Cellar/gcc/11.2.0_2 --enable-languages=c,c++,objc,obj-c++,fortran --with-gmp=/opt/homebrew --build=aarch64-apple-darwin21 --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk`
2. The error is very early, it's in stage 1 libgomp's configure:

```
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/ibin/aarch64-apple-darwin21/libgomp':
configure: error: cannot run C compiled programs.
```
3. We do not see it on Big Sur with the same exact setup
4. libgomp is not built yet.

---

The configure failure is as follows. libgomp's configure is trying to run the stage 1 compiler like this:

```
/tmp/ibin/./gcc/xgcc -B/tmp/ibin/./gcc/ -B/tmp/homebrew/Cellar/gcc/11.2.0_2/aarch64-apple-darwin21/bin/ -B/tmp/homeb
rew/Cellar/gcc/11.2.0_2/aarch64-apple-darwin21/lib/ -isystem /tmp/homebrew/Cellar/gcc/11.2.0_2/aarch64-apple-darwin21/include -isyst
em /tmp/homebrew/Cellar/gcc/11.2.0_2/aarch64-apple-darwin21/sys-include   -fno-checking -o conftest -g -O2   conftest.c
```

Compilation succeeds, but running the executable produced fails with:

```
dyld[53553]: Library not loaded: @rpath/libgcc_s.1.1.dylib
  Referenced from: /private/tmp/ibin/aarch64-apple-darwin21/libgomp/conftest
  Reason: tried: '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)
zsh: abort      ./conftest
```

And the output of `otool -lv` is:

```
meau /tmp/ibin/aarch64-apple-darwin21/libgomp $ otool -lv ./conftest        
./conftest:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot ---
 initprot ---
   nsects 0
    flags (none)
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x0000000000004000
  fileoff 0
 filesize 16384
  maxprot r-x
 initprot r-x
   nsects 3
    flags (none)
Section
  sectname __text
   segname __TEXT
      addr 0x0000000100003fc0
      size 0x0000000000000000
    offset 16320
     align 2^0 (1)
    reloff 0
    nreloc 0
      type S_REGULAR
attributes PURE_INSTRUCTIONS SOME_INSTRUCTIONS
 reserved1 0
 reserved2 0
Section
  sectname __text_startup
   segname __TEXT
      addr 0x0000000100003fc0
      size 0x0000000000000008
    offset 16320
     align 2^4 (16)
    reloff 0
    nreloc 0
      type S_REGULAR
attributes PURE_INSTRUCTIONS SOME_INSTRUCTIONS
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x0000000100003fc8
      size 0x0000000000000038
    offset 16328
     align 2^3 (8)
    reloff 0
    nreloc 0
      type S_REGULAR
attributes (none)
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000100004000
   vmsize 0x0000000000004000
  fileoff 16384
 filesize 709
  maxprot r--
 initprot r--
   nsects 0
    flags (none)
Load command 3
      cmd LC_DYLD_CHAINED_FIXUPS
  cmdsize 16
  dataoff 16384
 datasize 56
Load command 4
      cmd LC_DYLD_EXPORTS_TRIE
  cmdsize 16
  dataoff 16440
 datasize 48
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 16496
   nsyms 10
  stroff 16656
 strsize 152
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 8
     iextdefsym 8
     nextdefsym 2
      iundefsym 10
      nundefsym 0
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 0
  nindirectsyms 0
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 8
     cmd LC_UUID
 cmdsize 24
    uuid 54569743-313E-395E-AC41-05FBDB9CA11F
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 12.0
      sdk 12.0
   ntools 1
     tool LD
  version 711.0
Load command 10
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 11
       cmd LC_MAIN
   cmdsize 24
  entryoff 16320
 stacksize 0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libgcc_s.1.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.1.0
compatibility version 1.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1311.0.0
compatibility version 1.0.0
Load command 14
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 16488
 datasize 8
Load command 15
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 16496
 datasize 0
Load command 16
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 16816
 datasize 277
```

**Comment by fxcoudert** [comment]
Summary:
- I have not idea where the `/usr/local` comes from, I surely didn't put it in there.
- There is no rpath in the `conftest` executable
- libgcc_s is in a couple of places:

```
-rwxr-xr-x  1 fx  wheel    92K Nov 24 10:18 aarch64-apple-darwin21/libgcc/libgcc_s.1.1.dylib
-rwxr-xr-x  1 fx  wheel    76K Nov 24 10:18 aarch64-apple-darwin21/libgcc/libgcc_s.dylib
-rw-r--r--  1 fx  wheel    92K Nov 24 10:18 gcc/libgcc_s.1.1.dylib
```

`aarch64-apple-darwin21/libgcc` is not in any of the `-B` options. `gcc` is, but the `libgcc_s.1.1.dylib` there is not executable(?)

**Comment by ilg-ul** [comment]
The problem occurs when the configure test tries to run the `conftest` executable, since it does not have a rpath.

Try adding it to the linker.

**Comment by iains** [comment]
(caveat, testing is still running - but bootstrap completed).

there are three branches which reflect the [1..3] above:
[2] is on top of [1]
[3] is on top of [2]

[1] https://github.com/iains/gcc-11-branch/tree/gcc-11-2-darwin-nov21-backports
- these are patches already applied to master, but which fix code-gen, configure, test or abi issues and I intend to apply them to the branch before 10.3.  NOTE: this does not include all my patches (e.g. for coroutines) or patches that others might back port that will affect the outcome before 10.3.  This includes the patches needed to support cross-compilers on aarch64-darwin.

[2] https://github.com/iains/gcc-11-branch/tree/gcc-11-2-darwin-nov21-WIP
 - this is current WIP that has been posted and/or tested for supporting PCH on hosts with PIE .. it is relevant for both M1 host and target use.

[3] https://github.com/iains/gcc-11-branch/tree/gcc-11-2-darwin-nov21-apple-si
-This is the main native code support, as you can see this patch list is getting shorter as we apply stuff to master.

So .. I built [2] on x86_64-darwin21 and [3] on aarch64-darwin20.4

**Comment by fxcoudert** [comment]
Sure, if I manually add `-Wl,-rpath,/tmp/ibin/aarch64-apple-darwin21/libgcc` then it finds it. The question is: why doesn't the build mechanism do it (through the use of `-B`)?

**Comment by iains** [comment]
> Summary:
> 
> * I have not idea where the `/usr/local` comes from, I surely didn't put it in there.
> * There is no rpath in the `conftest` executable

that is what is broken.

The way that this is supposed to work is that (for each -B or known start files path) an rpath should be added to the exe.  This would include 'gcc' and aarch64/libxxxxx/.libs at build-time and then the /path/to/install/lib{,gcc-version/xxxx} when installed

The second mystery is why libgomp seems to want a shared libgcc (when that is not what's happening on x86 darwin20 or 21.

I have altered the default slightly so that (in the manner of clang) we default to a convenience lib for libgcc (like clang does with compiler-rt).  We only use a shared libgcc IFF (a) we have rpaths available || we are on <= darwin14  and (b) the compile line includes -shared-libgcc (which it does for c++ builds)

**Comment by fxcoudert** [comment]
```
meau /tmp/ibin $ grep -i rpath gcc/config.log
NOT using Darwin @rpath
NOT using Darwin @rpath
acl_cv_rpath=done
ENABLE_DARWIN_AT_RPATH_FALSE=''
ENABLE_DARWIN_AT_RPATH_TRUE='#'
enable_darwin_at_rpath=''
extra_opt_files=' $(srcdir)/config/aarch64/aarch64.opt $(srcdir)/config/rpath.opt $(srcdir)/config/darwin.opt'
```

Is that meant to be that way?

**Comment by ilg-ul** [comment]
> why doesn't the build mechanism do it (through the use of -B)?

I don't have an answer, but I noticed in my recent builds (after doing macOS builds for some years) that suddenly the resulting binaries no longer refer to libraries by absolute paths, but use `@rpath`.

For my releases this was not a big issue, since I have an explicit step of making the binaries relocatable, but some configure scripts failed.

It would be good to clarify this.

**Comment by fxcoudert** [comment]
In `libtool.m4`:

```
    # We cannot build and test reliably on macOS 10.11+ (Darwin15+) without use
    # of rpaths, since runpaths set via DYLD_LIBRARY_PATH are elided by key
    # system executables (e.g. /bin/sh).  Force rpaths on for these systems.
      UNSET,darwin1[[56789]]*|UNSET,darwin20*|10.1[[123456789]][[,.]]*|11.*[[,.]]* )
      echo "@rpath library names are needed on macOS versions later than 10.11 (rpaths enabled)" 1>&AS_MESSAGE_LOG_FD
      enable_darwin_at_rpath=yes
      ;;
```

notice that `11` is included, but not `12` or later? Could that be it? Why doesn't it manifest on Intel? So many questions…

**Comment by iains** [comment]
> > why doesn't the build mechanism do it (through the use of -B)?
> 
> I don't have an answer, but I noticed in my recent builds (after doing macOS builds for some years) that suddenly the resulting binaries no longer refer to libraries by absolute paths, but use `@rpath`.
> 
> For my releases this was not a big issue, since I have an explicit step of making the binaries relocatable, but some configure scripts failed.
> 
> It would be good to clarify this.

Since SIP was introduced, we have had a problem with GCC builds - since they rely on DYLD_LIBRARY_PATH being passed through configures (which no longer happens).

The eventual solution to this is to provide embedded run-paths (a.k.a rpaths) in the exe(s) and to have the libraries position-independent by default

**Comment by iains** [comment]
> In `libtool.m4`:


> notice that `11` is included, but not `12` or later? Could that be it? Why doesn't it manifest on Intel? So many questions…

Hmm .. I thought that was fixed in the "Darwin21" patch set. but, yes that could be the culprit.

**Comment by iains** [comment]
```
> meau /tmp/ibin $ grep -i rpath gcc/config.log
> NOT using Darwin @rpath
> NOT using Darwin @rpath
```

> Is that meant to be that way?

NO - and my copy of libtool.m4 seems to have 1[[12]] ... so barring the comment that we might be more forward-looking .. that ought to be OK.

**Comment by ilg-ul** [comment]
> The eventual solution to this is to provide embedded run-paths (a.k.a rpaths) in the exe(s)

Yes, when the details will be fully understood, this is probably the best solution. But is there any linker option to return to using absolute paths? This would probably make running tests more robust.

**Comment by iains** [comment]
you can configure with --disable-darwin-at-rpath but:

1. it will  misconfigure libstdc++ (as it has been since 10.11) because the availability of emulated TLS will not be detected.

2. I have not tested using that branch with --disable-darwin-at-rpath  (that patch set has been posted for review, but there is a little way more to go before it will be applied - I hope for gcc12 since it would be very sad to carry on with a broken configure &c.)

@fxcoudert 
I have a patch-in-progress to build a libgcc_s.1.dylib that works for older exes linked against libgcc_ext.10.x.dylib - it's hot off the press, so extra caveats, BUT if you get stuck with this release because of the missing libgcc_s.1.dylib - you can volunteer to be a guinea pig :)

**Comment by fxcoudert** [comment]
@iains I see, the libtool patch I am carrying in my tree (https://github.com/fxcoudert/gcc/commit/e4da6e2cc4072307771104bcad2fcd7a98fdb0c9) is an older version of yours (https://github.com/iains/gcc-darwin-arm64/commit/840865a947477f570af4732e988b76c82c75a99a#diff-4ccd091c8ac4d08370b548aee711e539a559d0c53d827782e292da0b97836a3f.patch)

I can fix that, now I know where it comes from.

**Comment by iains** [comment]
from the branches I posted you will need definitely the patches for host support, and the weakened emulated TLS symbols (they are in the back ports set).

I'd recommend the PCH set, that is also reviewed an awaiting an ack (so is very likely to make master soon)

You already know the story with the rpaths.

We have prototypes for the nested function support and for the ABI breaks, the initial versions posted - but the polishing there is likely to take some more time (most likely all stage3)

**Comment by ilg-ul** [comment]
@iains, if the previous comment was for me, yes, I can try to apply those patches, but, since my knowledge of the GCC internals is not that good, I'd prefer to use a fork with all the patches applied, as I did when I used the `https://github.com/fxcoudert/gcc/archive/refs/tags/gcc-11.1.0-arm-20210504.tar.gz` archive, which worked fain.

**Comment by iains** [comment]
> @iains, if the previous comment was for me, yes, I can try to apply those patches, but, since my knowledge of the GCC internals is not that good, I'd prefer to use a fork with all the patches applied, as I did when I used the `https://github.com/fxcoudert/gcc/archive/refs/tags/gcc-11.1.0-arm-20210504.tar.gz` archive, which worked fain.

it's easier for me to answer questions and respond to problems if you use the branch(es) I posted - but I understand that the homebrew folks might have additional constraints.

**Comment by iains** [comment]
(the comments were for everyone - since we have now got some of the aarch64 support on master, the back ports include necessary patches, not just improvements)

**Comment by fxcoudert** [comment]
@iains yes I know, I'm sorry, the Homebrew idea is really to go for maximal stability… it was already difficult to argue to ship a nonreleased version, so I am trying to update by minimal intervention. I try to solve as much as possible without bothering you, and I apologise for this issue. I'll close it now that I understand the issue.

**Comment by ilg-ul** [comment]
@iains, yes, your work is highly appreciated, but the same reasoning for the xPack GCC binaries, I generally try to stay close to a stable reference release. In this case, since upstream does not yet include support for Apple Silicon, I try to use Homebrew as reference, but otherwise for all other platforms I use GNU.

For special situations, like arm-none-eabi-gcc, which is based on an internal Arm fork of 10.3, and riscv-none-embed-gcc, which is based on a SiFive heavily modified fork of 10.2, I did manually apply the patches you were so kind to provide.

Thank you very much,

Liviu

**Comment by iains** [comment]
the trade-off between stability and functionality is understood ;)

FWIW, I use a gcc-7.5 based branch (but with back ported critical and necessary functional fixes) as my bootstrap compiler (since I build Ada, I cannot use clang).

It is, however, quite conventional for distributions to have "vendor branches" which provide [deemed] critical fixes between releases - so it's a question of choosing the right balance.

**Comment by iains** [comment]
test results on darwin20.4 for
gcc-11-2-darwin-nov21-apple-si revision r11-8916-gd419fec6afdd
configured as
"-prefix=/Users/iains/aarch64-apple-darwin20/gcc-11-2-wip --build=aarch64-apple-darwin20 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --enable-languages=all CC=aarch64-apple-darwin20-gcc CXX=aarch64-apple-darwin20-g++ --enable-pie-tools"
(using my previous aarch64-apple-darwin20-gcc (GCC) 11.2.0 as bootstrap)

-----

[summ-aarch64-darwin20-branch-on-gcc-11-2.txt](https://github.com/iains/gcc-darwin-arm64/files/7595755/summ-aarch64-darwin20-branch-on-gcc-11-2.txt)

**Comment by ilg-ul** [comment]
> xPack GCC ... I'd update the scripts to use gcc-11.2.0-arm-20211123

I did, actually I used the next release, `gcc-11.2.0-arm-20211124`, and the build passed, both on Intel and Apple Silicon Macs.

Thank you, @iains, @fxcoudert!

**Comment by carlocab** [comment]
> * I have not idea where the `/usr/local` comes from, I surely didn't put it in there.

This seems to come from a change in behaviour in Monterey `dyld`: https://openradar.appspot.com/FB9725981
