### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by ilg-ul** [iains/gcc-darwin-arm64#58]
I think it would be useful to enable Discussion for this project, since not necessarily all messages are bugs/enhancements. If they turn to be, topics can be later moved from Discussions to issues.

**Comment by iains** [comment]
I have mixed feelings about this.
GCC has irc channels for both User support and compiler developers and email lists likewise.

In the first instance we should be using those - there's no secret about this port.

The intent is that this repository will become obsolete (i.e. the content will become part of GCC).

... If there is something that needs the discussions channel that cannot be handled by the general GCC ones, then we should consider it, of course.

**Comment by iains** [comment]
OK, so what I suggest is:

* Iff there is a Darwin-specific discussion about building toolchains - please add it to 
https://github.com/iains/darwin-toolchains-start-here/discussions (which I have opened for this purpose).

* If the issue is generic GCC (including bugs) then it should be discussed on gcc@gcc.gnu.org (or gcc-patches@ and on the #gcc irc channe

*  generic bugs should be filed in https://gcc.gnu.org/bugzilla (they will possibly get lost if filed as issues against this branch).

As a reminder - this branch is not intended to be a fork of GCC, but just a convenient place to develop allowing for pull RQs, merges and so on that are more difficult to arrange elsewhere.

At some point, it would be good to capture  common issues/discussions and migrate those to the GCC Wiki.
