### ISSUE TITLE
Segfault in build/genmatch when building 

### ISSUE THREAD

**Issue by rhdtownsend** [iains/gcc-darwin-arm64#75]
Building HEAD (0c71be0cd8f) I run into the following issue:

build/genmatch --gimple /Users/townsend/devel/sdk2-tmp/build/gcc/gcc/match.pd \
	    > tmp-gimple-match.c
GIMPLE decision tree has 4092 leafs, maximum depth 17615 and a total number of 3174049648 nodes
removed 2717 duplicate tails
build/genmatch --generic /Users/townsend/devel/sdk2-tmp/build/gcc/gcc/match.pd \
	    > tmp-generic-match.c
GENERIC decision tree has 3734 leafs, maximum depth 15737 and a total number of 3174049648 nodes
/bin/sh: line 1: 91114 Segmentation fault: 11  build/genmatch --generic /Users/townsend/devel/sdk2-tmp/build/gcc/gcc/match.pd > tmp-generic-match.c
make[3]: *** [s-match] Error 139
make[3]: *** Waiting for unfinished jobs....
/bin/sh /Users/townsend/devel/sdk2-tmp/build/gcc/gcc/../move-if-change tmp-automata.c insn-automata.c
echo timestamp > s-automata
/bin/sh /Users/townsend/devel/sdk2-tmp/build/gcc/gcc/../move-if-change tmp-attrtab.c    insn-attrtab.c
/bin/sh /Users/townsend/devel/sdk2-tmp/build/gcc/gcc/../move-if-change tmp-dfatab.c     insn-dfatab.c
/bin/sh /Users/townsend/devel/sdk2-tmp/build/gcc/gcc/../move-if-change tmp-latencytab.c insn-latencytab.c
echo timestamp > s-attrtab
rm fsf-funding.pod gpl.pod cpp.pod gfdl.pod gfortran.pod gcc.pod gcov-tool.pod gcov.pod gcov-dump.pod
make[2]: *** [all-stage2-gcc] Error 2
make[1]: *** [stage2-bubble] Error 2
make: *** [all] Error 2

My configure is as follows:

/Users/townsend/devel/sdk2-tmp/build/gcc/configure CC=clang CXX=clang++ --build=aarch64-apple-darwin --host=aarch64-apple-darwin --target=aarch64-apple-darwin --prefix=/Users/townsend/devel/sdk2-tmp/mesasdk --with-gmp=/Users/townsend/devel/sdk2-tmp/mesasdk --with-mpfr=/Users/townsend/devel/sdk2-tmp/mesasdk --with-mpc=/Users/townsend/devel/sdk2-tmp/mesasdk --enable-languages=c,c++,fortran --disable-multilib --disable-nls --disable-libsanitizer --disable-darwin-at-rpath --with-sysroot=/Users/townsend/devel/sdk2-tmp/mesasdk/sysroot

(I'm using the disable-darwin-at-rpath because I handle rpath stuff myself when packaging gcc up with other stuff)

**Comment by iains** [comment]
> Building HEAD ([0c71be0](https://github.com/iains/gcc-darwin-arm64/commit/0c71be0cd8f0a93b735567105973aa27b1492c40)) I run into the following issue:

Which version of Xcode command line tools are you using?

> My configure is as follows:

> /Users/townsend/devel/sdk2-tmp/build/gcc/configure CC=clang CXX=clang++ --build=aarch64-apple-darwin --host=aarch64-apple-darwin --target=aarch64-apple-darwin --prefix=/Users/townsend/devel/sdk2-tmp/mesasdk --with-gmp=/Users/townsend/devel/sdk2-tmp/mesasdk --with-mpfr=/Users/townsend/devel/sdk2-tmp/mesasdk --with-mpc=/Users/townsend/devel/sdk2-tmp/mesasdk --enable-languages=c,c++,fortran --disable-multilib --disable-nls --disable-libsanitizer --disable-darwin-at-rpath --with-sysroot=/Users/townsend/devel/sdk2-tmp/mesasdk/sysroot

(JFTR, --disable-multilib is not needed)

Your sysroot is some kind of hybrid of Apple's SDK and some additions?

> (I'm using the disable-darwin-at-rpath because I handle rpath stuff myself when packaging gcc up with other stuff)

Hmm.. I am not sure what effect that might have - it might well misconfigure some parts of the system - let me try a build and see,  we're in fairly early days here and non-default configure options have not been kicked around much ...

Having the runtimes with @rpath names ought to short-circuit some of your post-processing?

**Comment by iains** [comment]
--enable-pie-tools might be a thing to add tho.

**Comment by iains** [comment]
unfortunately, I can't reproduce that fail either;
```
$ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
```
```
..../gcc-master/configure --prefix=/Users/iains/aarch64-apple-darwin20/gcc-12-0-0 --build=aarch64-apple-darwin20 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --enable-languages=all CC=clang CXX=clang++ --enable-pie-tools --disable-darwin-at-rpath >conf.txt
configure: WARNING: using in-tree isl, disabling version check
configure: WARNING: GNAT is required to build ada
configure: WARNING: GDC is required to build d
configure: WARNING: go not supported for this target
*** This configuration is not supported in the following subdirectories:
     target-libsanitizer target-libvtv target-libphobos target-libffi target-libgo gnattools gotools target-libada target-zlib target-liboffloadmic
    (Any other directories should still work fine.)
rm: conftest.dSYM: is a directory
bash-3.2$ time nice make -j8 >b.txt 2>e.txt && time make install >ins.txt 2>ine.txt 

real	40m40.896s
user	222m38.450s
sys	13m45.834s

real	0m9.344s
user	0m3.964s
sys	0m4.052s
```

**Comment by rhdtownsend** [comment]
Here's my version info:

Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Regarding the rpath stuff -- I use the convention that @rpath points to $prefix, rather than $prefix/lib. So, dylibs end up with install names of the form @rpath/lib/libgfortran.dylib.

And regarding sysroot -- this is just a symlink to the Apple SDK. When my packages get deployed, the symlink is updated to point to their local installation of the SDK.

**Comment by iains** [comment]
hmm .. I'm using a farm machine - so I cannot choose the Xcode there.  However I can try cross and native cross complies.  At which stage does your build fail?

**Comment by iains** [comment]
> Regarding the rpath stuff -- I use the convention that @rpath points to $prefix, rather than $prefix/lib. So, dylibs end up with install names of the form @rpath/lib/libgfortran.dylib.

On any system with SIP engaged (which it should be), the GCC configuration process cannot work with a shared libgcc_s without an ```@rpath ``` solution in which the compiler and the library names are compatible, (the compiler needs to be able to insert run paths to find the runtimes at build-time).

I need to double-check that we have disabled the shared libgcc in the case that the configuration disables the compiler's @rpath solution.

( given that you see a segv rather than an abort I suspect that the problem is not that the library cannot be found ).

**Comment by rhdtownsend** [comment]
On Dec 27, 2021, at 5:48 PM, iains ***@***.******@***.***>> wrote:



Regarding the rpath stuff -- I use the convention that @rpath<https://github.com/rpath> points to $prefix, rather than $prefix/lib. So, dylibs end up with install names of the form @rpath/lib/libgfortran.dylib.

On any system with SIP engaged (which it should be), the GCC configuration process cannot work with a shared libgcc_s without an @rpath solution in which the compiler and the library names are compatible, (the compiler needs to be able to insert run paths to find the runtimes at build-time).

I need to double-check that we have disabled the shared libgcc in the case that the configuration disables the compiler's @rpath<https://github.com/rpath> solution.

( given that you see a segv rather than an abort I suspect that the problem is not that the library cannot be found ).


Is this new behavior specific to gcc 12? I’ve had things working fine for quite a while in gcc 10 and 11 builds. Indeed, I built gcc 12 just fine a week ago — this issue seems to have arisen since then.

cheers,

R

**Comment by rhdtownsend** [comment]
Here's the full build log
[install.log.gz](https://github.com/iains/gcc-darwin-arm64/files/7782649/install.log.gz)

**Comment by rhdtownsend** [comment]
Further update: I've tried building with a trimmed-down configure, along the lines of the one you posted above:

/Users/townsend/devel/sdk2-tmp/build/gcc/configure CC=clang CXX=clang++ --build=aarch64-apple-darwin --prefix=/Users/townsend/devel/sdk2-tmp/mesasdk --with-gmp=/Users/townsend/devel/sdk2-tmp/mesasdk --with-mpfr=/Users/townsend/devel/sdk2-tmp/mesasdk --with-mpc=/Users/townsend/devel/sdk2-tmp/mesasdk --enable-languages=c,c++,fortran --enable-pie-tools --disable-nls --disable-libsanitizer --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

Alas, same outcome.

**Comment by iains** [comment]
please could you amend to 
--build=aarch64-apple-darwin20 or aarch64-apple-darwin21.

I'll take a look at the log.

**Comment by iains** [comment]
"Warning: libgcc configured to support macOS 10.5"

- might be a source of some problems.

explanation:

If you do **not** put --build= { --host= --target=}  then the configure process uses the value returned by the kernel (so configures for the machine you are on).

If you put --build=aarch64-apple-darwin then there is no major number for the configure to use, and it falls back to some common version - currently 10.5 since that supported both ppc and x86.

if you put --build=aarch64-apple-darwinN then N is the version of the OS it will configure for (if N < than the one you are on, and you are really intending to deploy to it, then you also should use the right SDK and build with MACOSX_DEPLOYMENT_TARGET=N)
In practice, it is usually OK to build for current-1 but there can be gotchas with SDK stuff, so it's best to use the SDK for the target.

I guess we could change the fallback for aarch64 if that is causing your troubles here.

Unfortunately, I cannot deduce much more from the log (we are failing in the initial compilations of stage2 - so either the stage1 compiler and/or libraries have problems) - running the failing command line under lldb and producing a backtrace could be helpful.

**Comment by iains** [comment]
incidentally, when I looked at (admittedly earlier) versions of clang supporting macOS arm64, I tried various permutations of xxx-apple-darwinYYY/xxx-apple-macosxZZ .. to see what got passed to the compilation and link phases

... ISTR that the clang driver would map earlier darwin to iOS - and 0 (i.e an absent major number) would count as an earlier version.

It is becoming tricky to work without some choice of major number, since the OS has changed a lot over the years, and we now have a fair number of configuration conditionals that use the major number, we'd need to go through all those and choose some suitable value for aarch64-darwin;

I guess the bottom line is "what does that configuration value give you that is better than choosing the minimum OS version you want to support - and building accordingly"

**Comment by rhdtownsend** [comment]
Bingo: setting the --build=aarch64-apple-darwin20 allows compilation without problem.

I used to have a version number in the build string, but got rid of it because some packages were complaining that I was building on an unreleased version of MacOS. This may have been because I was pulling the version number from 'uname -r' (rather than hardwiring it as above). 

So, this is very much a self-inflicted problem; apologies, but thanks for the time you put in to solving it!
